#!/usr/bin/env bash
# HELIX PR Generator (v3.0) — Automatic PR creation with Adversarial Review
# This script handles PR generation and triggers the Adversarial Agent.

set -euo pipefail

# Detect HELIX_HOME
if [[ -d "$(pwd)/.helix" ]]; then
  HELIX_ROOT="$(pwd)"
else
  HELIX_ROOT="${HOME}/.claude/skills/helix"
fi

PR_TEMPLATE="${HELIX_ROOT}/templates/specialists/pr-description.md"

# ─── PR Generation ────────────────────────────────────────────────────────────

generate_pr() {
  local branch=$(git rev-parse --abbrev-ref HEAD)
  local base_branch="${1:-main}"
  
  echo "Generating PR description for branch: $branch"
  
  # In a real scenario, we would use the LLM to summarize the diff
  # For this prototype, we'll output a placeholder and inform the orchestrator
  
  local diff_stat=$(git diff --stat "$base_branch")
  
  cat <<EOF > .helix/state/last_pr_description.md
# HELIX Automated PR: $branch

## Summary
Auto-generated by HELIX v3.0 Evolver.

## Changes
$diff_stat

## Adversarial Review Status
[PENDING]
EOF

  echo "PR description generated at .helix/state/last_pr_description.md"
  echo "Spawning Adversarial Review Agent..."
  # Hand off to LLM via Agent tool
}

# ─── Main ─────────────────────────────────────────────────────────────────────

main() {
  local cmd="${1:-help}"
  shift || true

  case "$cmd" in
    generate) generate_pr "$@" ;;
    help|--help)
      echo "HELIX PR Generator v3.0"
      echo ""
      echo "Commands:"
      echo "  generate [base_branch]    Generate PR description and trigger review"
      ;;
    *) echo "Unknown command: $cmd. Try: helix-pr-gen.sh help" ;;
  esac
}

main "$@"
